cores: &cores 8

fastqc:
    o: '{output_dir}'

fastq-mcf:
    l: 50  # Minimum remaining sequence length
    q: 20  # Quality threshold causing base removal
    x: 10  # 'N' percentage causing cycle removal
    P: 33  # Phred-scale
    u: ''  # Force enable Illumina PF filtering

bwa:
    M: '{reference_genome}'
    # ^ If you want to change the build used as reference,
    # modify the &reference_genome_default in resources.yml
    t: *cores

picard-tools:
    AddOrReplaceReadGroups:
        VALIDATION_STRINGENCY: LENIENT
        SO: coordinate
        CREATE_INDEX: TRUE
        PL: ILLUMINA
        PU: 000000000-D0M8G.1
        ID: '{ngs_id}.{library_id}.000000000-D0M8G.1.{sample_id}'
        SM: '{sample_id}'
        LB: '{library_id}'
        I: '{input}'
        O: '{output}'
    CollectAlignmentSummaryMetrics:
        R: '{reference_genome}'
        I: '{input}'
        O: '{output}'
        ADAPTER_SEQUENCE: 'null'
    CollectVariantCallingMetrics:
        SD: '{reference_genome_dict}'
        GVCF_INPUT: 'true'  # run on a single-sample gVCF
        DBSNP: '{known_variants}'
        I: '{input}'
        O: '{output}'

GATK:
    defaults: &gatk_defaults
        T: '{module_name}'
        R: '{reference_genome}'
        I: '{input}'
        o: '{output}'

    RealignerTargetCreator:
        <<: *gatk_defaults
        L: '{limits}'

    IndelRealigner:
        <<: *gatk_defaults
        targetIntervals: '{target_intervals}'

    BaseRecalibrator:
        <<: *gatk_defaults
        L: '{limits}'
        nct: *cores

    PrintReads:
        <<: *gatk_defaults
        BQSR: '{recalibration}'
        nct: *cores

    DiagnoseTargets:
        <<: *gatk_defaults
        L: '{limits}'

    HaplotypeCaller:
        vcf:
            <<: *gatk_defaults
            gt_mode: DISCOVERY
            L: '{limits}'
            stand_emit_conf: 10
            stand_call_conf: 30
            nct: *cores
        gvcf:
            <<: *gatk_defaults
            gt_mode: DISCOVERY
            L: '{limits}'
            stand_emit_conf: 10
            stand_call_conf: 30
            nct: *cores

            ERC: BP_RESOLUTION
            variant_index_parameter: 128000
            variant_index_type: LINEAR
            # The gVCF output from BP_RESOLUTION contains extra info about the
            # confidence of a 0/0 call. This differs from an "all-sites" VCF
            # produced with EMIT_ALL_CONFIDENT_SITES
            # out_mode: EMIT_ALL_CONFIDENT_SITES

    GenotypeGVCFs:
        T: GenotypeGVCFs
        R: '{reference_genome}'
        D: '{known_variants}'
        o: '{output}'
        nda: ''  # Annotate discovered alleles (not necessesarily genotyped)
        allSites: ''  # Include non variant sites!
        nt: *cores

    SelectVariants:
        defaults: &select_variants_defaults
            T: SelectVariants
            R: '{reference_genome}'
            V: '{input}'
            o: '{output}'
        snps:
            selectType: SNP
            <<: *select_variants_defaults
        indels:
            selectType: INDEL
            <<: *select_variants_defaults

    VariantFiltration:
        T: VariantFiltration
        R: '{reference_genome}'
        V: '{input}'
        o: '{output}'

    VariantFiltration_filters:
        # Order in which to apply the filters, since dict keys are unordered.
        # These filters will be applied after the joint genotyping and
        # across all samples of the cohort, following the directions found
        # here: http://gatkforums.broadinstitute.org/gatk/discussion/2806/
        # howto-apply-hard-filters-to-a-call-set

        snps:
            - 'QD < 2.0'
            - 'MQ < 40.0'
            - 'MQRankSum < -12.5'
            - 'ReadPosRankSum < -8.0'
            # - 'FS > 60.0'
            # - 'SOR > 4.0'
        indels:
            - 'QD < 2.0'
            - 'ReadPosRankSum < 20.0'
            # - 'FS > 200.0'
            # - 'SOR > 10.0'
            # - 'InbreedingCoeff < -0.8'  # Only for more than 10 samples
        genotype:
            - 'GQ < 30.0 && RGQ < 30.0'
            - 'DP < 50.0'

    CombineVariants:
        T: CombineVariants
        R: '{reference_genome}'
        genotypeMergeOptions: PRIORITIZE
        o: '{output}'

SnpEff:
    reference_genome: hg19
    v: ''

VEP:
    everything: ''  # Boolean flags with no value.
    offline: ''
    merged: ''  # Because I'm using the merged VEP+RefSeq cached genome
    stats_file: '{stats_file}'


